version: '3.7'
services:
  fastapi-test:
    build: .
    volumes:
      - /home/hima/gitlab/terraform:/opt/terraform
    ports:
      - '8000:8000'
    restart: always
      #nginx:
      #image: nginx:alpine
      #restart: always
      #volumes:
      #- ./nginx/nginx.conf:/etc/nginx/nginx.conf
      #ports:
      #- "80:8000"
      #depends_on:
      #- fastapi-test

